version: '3.8'

services:
  bot-api:
    build: ./
    command: npm run server
    working_dir: /usr/src/bot-api
    ports:
      - "4000:4000"
    volumes: 
      - ./:/usr/src/bot-api
    environment:
      MONGO_URI: "mongodb://test:test@mongodb:27017/bestbot"

  mongodb:
    image: mongo:4.4.3
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_ROOT_DB: admin
    ports: 
      - "27017:27017"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro